/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 19.05.2026 16:42:30

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1456;
#else
constexpr int kTensorArenaSize = 432;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,84 } };
const TfArray<1, float> quant0_scale = { 1, { 0.073304750025272369, } };
const TfArray<1, int> quant0_zero = { 1, { -74 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[3] = { -293, 307, -33, };
const TfArray<1, int> tensor_dimension1 = { 1, { 3 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00037119796616025269, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[3*10] = { 
  69, 12, 98, -72, -25, 68, 61, -111, -110, 80, 
  56, 68, -21, -91, -127, -10, 57, -77, 7, -24, 
  -92, -20, 114, -4, -97, -89, -117, -38, 103, 31, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 3,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0058415960520505905, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { -78, 22, 0, -99, 136, 153, 379, 428, -231, -118, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00013310082431416959, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  37, -76, -72, 5, 127, 9, 100, -100, -5, -39, 39, 12, 52, 99, 45, -79, -5, -28, -64, 22, 
  -51, -106, 60, 59, 49, -37, -48, -88, -85, 17, -44, -50, 57, 19, 63, 83, -47, 30, -38, -28, 
  -21, -88, -3, 96, -44, -54, -32, 19, -37, -10, 29, 46, -20, -79, -12, -63, 77, -89, -91, -74, 
  54, 12, 86, 12, -56, 71, -55, -45, -26, 67, 89, 43, -61, -88, -7, -44, -24, -46, 96, 77, 
  -41, 53, -95, -43, -89, 49, -20, 12, -84, 52, 97, 53, -32, 37, 24, -101, -57, 96, 65, 53, 
  -80, 66, -69, 43, -50, -110, 1, 68, -106, -44, 88, 53, -51, 55, -22, -64, -38, 55, -61, 4, 
  84, 58, -69, -91, 91, 82, 25, -19, -24, 5, 75, 32, -66, -28, 15, -5, 62, -18, -14, -32, 
  -14, 108, 66, 74, 3, 99, 96, -85, 104, -26, -69, 118, 79, -10, -79, 64, 98, 17, 10, 77, 
  57, 24, 50, 35, 57, 22, -108, -32, -27, 11, 77, 2, -8, -103, -39, 80, -91, 58, -44, -30, 
  40, -71, -21, -4, 65, 88, -21, 6, 70, -88, -61, 41, -71, -53, 49, -21, -21, 78, 2, 70, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.004201910924166441, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 0, 271, 171, 167, 204, 152, 227, 71, 0, 6, 432, 304, 46, 71, -5, -117, 208, 68, -50, 0, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00019569866708479822, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*84] = { 
  0, -12, -20, 73, 25, 43, 25, -57, 29, -71, -3, 32, -78, -58, -19, 78, 22, 64, -43, -43, 76, -23, 74, 16, -81, 56, -43, -44, -61, -80, 21, 27, 53, -73, -83, 38, -55, 64, -8, -57, 40, -8, -66, -27, -77, 73, -31, 77, -58, -64, -16, -83, 35, -19, -75, 56, 84, 66, 87, 52, 33, -36, 9, -63, -14, -62, 1, 28, 75, -11, 21, -75, -55, -23, -19, -48, 61, 41, -12, 73, 24, -3, -15, 27, 
  -65, 11, 90, 24, -35, 12, 29, 2, 56, 79, -79, 35, 27, 30, 75, -27, 89, 31, 85, -43, -8, 16, 77, -15, 34, 44, -33, 72, -1, -53, -2, 53, 45, 117, 91, -34, -90, 23, 55, -9, -50, -36, 106, 82, 71, -35, 55, -48, 17, -8, -81, -1, 2, -24, -4, -101, -56, 101, 104, -91, -40, 90, -4, 6, -41, 22, 89, -67, 33, -9, 105, -31, 72, -30, -20, 105, -1, -41, 10, 102, 10, -67, -32, 11, 
  71, 0, -61, -96, 8, -23, 73, 65, 94, 16, -32, 38, -54, 54, -39, 74, 41, 30, -25, 63, 113, -85, 41, -45, 22, 2, 75, 57, -33, -57, -33, 39, 17, -37, 11, -12, -86, 17, 80, -45, 34, 57, -70, -2, 44, -40, -67, -51, 55, -19, 46, 3, -14, 21, 58, -60, 23, 27, 23, -37, 93, -18, -1, 28, -37, 64, 31, -37, -39, -17, 9, -74, 19, 62, -31, -59, -63, 48, -32, -41, 48, -36, 44, 9, 
  -61, 59, -35, 43, -18, 32, 3, 74, 57, -63, 80, 83, 55, 67, 50, -8, -56, -54, 19, 66, -47, 41, -60, -22, 54, 57, -76, 65, 86, 70, -27, 25, 65, -29, 64, 23, 75, -74, 17, 72, -86, 66, 13, 81, 97, -80, -14, -47, 64, 41, -57, 8, -17, -78, 33, -54, -64, -75, -24, -23, 93, 42, 96, 76, -71, -68, 63, -64, -68, -69, 63, -34, -36, -76, 8, 41, -10, 90, 41, 98, 27, 69, 74, -15, 
  89, 51, 50, -100, -100, -32, 116, 14, -57, 93, 21, 57, -106, -42, -48, 56, 60, 22, -45, 14, 29, 54, -23, 26, -5, 44, 91, 87, -66, -31, 81, -54, 98, -80, -38, -2, -6, -93, -10, 40, -12, 26, -63, -23, 60, -87, 32, 85, 14, 76, 57, 96, -66, 9, -42, 90, 46, 53, 48, 36, -19, -95, 52, 90, -11, 59, -34, 97, -117, 12, -73, 42, 80, 36, 64, 14, -42, -23, -40, -32, 56, -82, 81, -22, 
  -15, 77, 19, -6, -30, -70, 13, 96, -26, 22, -80, -29, -80, 50, 26, 9, -70, 26, -25, 6, -70, -91, -14, -44, 65, -23, 17, 0, -31, 98, -6, -9, 75, -60, 17, -73, 63, -55, 28, 75, 52, 42, -50, -14, 26, -89, -70, -57, 0, 56, 78, -11, 30, -34, 46, 40, 34, -10, 50, -5, 40, -83, 51, -59, -36, 10, -22, 82, 65, 52, 93, -29, 72, -74, -78, -68, -3, -21, 64, 10, -63, 43, -31, 83, 
  60, -11, -14, -73, -72, -69, -6, 55, -38, 30, 28, 16, -3, 48, 52, 2, -20, -64, 68, 87, -23, 28, -42, 78, -15, 12, 94, -71, 89, 28, 65, -95, -11, 1, -57, 57, -83, 49, -61, 101, -7, 14, 10, 20, -28, -93, 69, -31, 8, -12, -59, 91, -72, 72, 40, 7, 21, 86, 60, -48, -64, 22, 75, -37, 26, 40, -64, 73, -80, -36, 30, 96, -9, 26, 15, 65, 56, 72, 52, -23, 80, 71, 14, 33, 
  73, -87, 29, 85, 72, 25, 18, 9, -23, 69, -38, 80, -31, 32, -52, -80, -24, -51, -61, 86, 74, -31, -41, -4, -30, 83, -31, 14, -79, -21, 12, 66, -3, -58, -14, -94, -33, 42, 83, -12, -13, 21, 95, 92, 37, -12, 17, -73, -51, 35, -61, -22, -18, 16, -25, -52, -61, 79, 80, -93, -95, -9, 68, -58, 42, 31, 30, -30, -41, 86, -43, 19, -13, 24, -24, 38, -18, 58, -42, 52, 99, -79, 48, -12, 
  49, 85, 53, -15, -76, 55, -10, -53, -7, -14, 6, 54, 52, -32, 14, -38, 37, -41, 88, 18, 82, 60, 80, 36, 55, 57, 64, -8, 74, -78, 50, -84, -13, -1, -73, -25, -78, 75, -59, 8, -45, -46, -81, -34, -78, 26, -31, -11, -46, 27, -82, -87, 88, -56, 46, 43, 12, 42, -9, -33, 57, -20, 75, -35, 5, -85, 77, 64, 55, -45, -38, -27, 15, -72, -28, -80, -65, -40, -50, 75, -44, -51, -69, -41, 
  -74, 41, -74, -6, -55, 47, -81, -5, -52, -90, -78, -62, -89, -22, -56, 70, -9, 54, 63, -57, -21, 56, 17, 81, 89, 58, 8, 28, -2, 42, -38, -26, -64, -3, 63, 27, 59, 68, -13, 13, 19, 40, -48, 22, -37, -89, 57, 37, 77, -69, 46, 85, -86, -84, -53, 17, 50, 10, -80, 27, -79, -49, -61, 68, 1, -21, -83, -25, -62, 38, -56, 59, 78, 2, -17, -67, 82, -25, -88, 62, 45, 86, -76, -50, 
  118, 45, 65, -88, -92, -22, 58, -16, 5, 38, -82, 35, 59, -108, 75, -19, 32, -24, 15, 41, -57, 73, -72, 84, 68, -2, -75, -44, 95, 58, -86, -108, -110, 19, 127, 86, -42, -32, -30, 63, 63, -52, 37, 5, 4, 39, -14, -61, 73, 33, -29, -35, -17, 15, 67, 66, -21, 1, 60, -46, -20, 70, 98, 92, -9, -53, -46, 73, 17, 42, 104, 40, 10, -72, -41, 119, 62, -41, 63, 123, -6, -27, 40, -62, 
  14, 46, 102, -28, -84, -69, 95, -57, 72, -14, 67, 89, 64, 85, -9, 63, -14, -49, 67, 19, -6, 5, 92, 14, 23, 46, 44, 42, 114, 39, -2, -46, -23, -10, 50, -25, -71, 49, 50, 74, 35, 66, 100, 8, -25, -45, 4, 59, -61, -11, -67, 76, 27, 46, 92, 40, 74, 13, 41, -94, 45, 78, 27, -1, 41, 78, 84, 2, -33, -9, -40, 24, -29, -82, 44, 52, 69, 75, 56, 41, 65, 107, -65, -44, 
  -43, -79, -5, -27, 59, -80, -51, -102, -75, 43, -16, -83, 38, 66, -30, 69, 15, -21, 80, -32, 35, 32, -61, 52, 44, -32, -1, -23, 76, -8, -23, 33, -70, 64, 41, 46, 83, -73, -94, -70, -28, 33, -69, -40, -85, -31, 85, 46, -15, 88, 61, -81, -89, 14, -47, -73, -71, 15, -33, 35, 3, -76, -85, 64, 10, 24, 60, 36, 0, 70, -4, -38, 45, 59, 41, -105, -42, 56, -76, -77, 12, 39, 84, 69, 
  34, -92, -38, -10, 69, 96, -70, 66, -17, 28, 12, 30, 72, 16, -9, -58, -84, -25, -82, -23, -59, -53, 3, -21, -40, -81, -56, 67, -7, -2, 19, -102, -82, -71, 2, 14, 35, 9, 88, -12, 91, 35, 78, -60, 80, -55, -14, 61, 99, 52, 28, 52, -64, -33, 86, -30, 31, 78, 62, -21, -16, -14, 2, -60, 53, 76, 83, 78, 20, 80, -60, -13, 60, -32, 26, -49, -32, -37, 47, -41, -22, 51, -32, -39, 
  93, -84, -35, 4, -9, -38, -27, 24, 31, 43, 98, -75, -90, 72, -85, -35, -80, -2, 37, -57, 88, 99, -42, 78, -76, -40, -1, -86, 73, -39, 76, -66, -59, 72, 3, -50, -69, 37, 88, -65, -75, 58, -86, 55, -16, 39, -48, -43, -72, -32, -20, 54, 31, -1, -72, -52, 96, -5, 93, -50, -13, 54, -36, 84, 13, 82, 81, 57, -9, 38, 22, -56, 79, -47, 60, 59, -24, 27, -2, 13, 57, 15, -71, -54, 
  -15, 77, -78, -81, -72, 15, -14, 33, 37, 24, 4, 29, -42, 52, 31, 59, 5, 51, 40, 42, -91, 55, -82, 31, 25, -7, -44, -19, -28, -37, 35, -14, -14, 29, -24, 24, 7, -100, 4, 61, 41, -32, 17, -73, 54, -43, -69, -34, -76, 65, 39, -18, 61, 65, 30, -49, 59, 21, -85, 83, 22, -75, -3, -51, 22, 25, -1, -65, 6, 64, -94, 66, 65, 94, 56, 45, -56, 14, 68, 18, -79, -67, 20, 95, 
  17, -40, -14, -42, 49, 5, 2, -61, 35, -46, -37, 4, 29, 54, -16, 47, -56, -70, 10, -4, -47, -49, 26, -8, 64, 1, -19, 86, -47, 84, 53, -11, 62, -46, -18, -28, 25, -68, -35, 12, -13, -4, 30, 79, 4, -94, 46, -60, 15, -20, 7, 12, -11, -42, -5, -64, -3, -10, 63, -78, -49, 85, -46, 21, -78, 55, 15, -19, -20, 104, -60, -2, -30, 65, 61, 53, -31, 26, -40, 31, 30, 93, -70, -8, 
  -9, 45, 83, 77, 58, -25, -41, 49, 40, -18, -58, 81, -31, 61, -58, -24, -57, 21, 84, -46, 47, -17, -59, 83, -62, -74, -51, 23, -1, -56, -16, -87, -23, 47, 32, 79, 76, -25, 90, -52, -82, -29, 95, -22, 32, -64, 4, 90, -62, 38, -41, -47, 82, 52, 35, -70, 83, -58, 3, -47, -15, -51, 66, 90, -23, 54, -2, 8, 28, -26, 79, -29, 61, 70, 17, 46, -58, -56, 70, -61, -62, -73, -81, 10, 
  -79, -27, 44, -84, 47, 4, -62, -12, -1, -35, -86, -38, -73, -67, -70, -50, 2, -49, -45, 31, -48, 73, -49, 67, -40, -82, -6, -28, -83, -66, 37, -35, -53, -84, 85, 68, 24, -64, -72, -33, -62, 21, -57, 42, -1, -10, 93, 17, -74, -83, 5, -80, 40, -55, 60, -65, -62, -60, -28, 68, -32, -50, -63, 66, 48, -50, 74, -76, 8, 75, 52, 45, 64, -37, -81, 24, 76, 16, -27, 27, 24, 34, 74, -6, 
  -3, 67, 5, -44, -15, -29, 27, -12, 64, 61, -72, 71, 62, -1, -1, -37, -2, -75, -48, 24, -34, -82, 70, -70, -6, 2, -58, -38, 32, 71, -62, 13, 76, -56, 8, 31, -82, 19, 5, -11, -59, -62, 24, 50, 1, -72, -83, 24, -9, 3, 23, 41, -76, 30, 41, -46, 47, -75, -60, 75, -69, 60, -66, 32, -67, -10, -14, -61, -65, -53, -86, 59, -26, -12, -19, 30, -75, -88, -78, -40, 69, -6, -3, -76, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,84 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0026696587447077036, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.031676258891820908, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.063543930649757385, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,3 } };
const TfArray<1, float> quant9_scale = { 1, { 0.046188253909349442, } };
const TfArray<1, int> quant9_zero = { 1, { 102 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 84, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 30, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 1680, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 96), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_998581_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_998581_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_998581_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_998581_3_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_998581_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
